# Farben von aether (wird bei jedem Theme-Wechsel neu generiert)
include ~/.config/aether/theme/kitty-colors.conf

# Transparenz
background_opacity 0.85

# Cursor
cursor #7aa2f7

# Keine Terminal-Glocke
enable_audio_bell no

# Schrift
font_family JetBrainsMono Nerd Font
font_size 11
