# Background and foreground colors
background = #1a1b26
foreground = #c0caf5

# Standard colors
palette = 0=#1a1b26
palette = 1=#f7768e
palette = 2=#a6e3a1
palette = 3=#f9e2af
palette = 4=#1793d1
palette = 5=#cba6f7
palette = 6=#89dceb
palette = 7=#c0caf5

# Bright colors
palette = 8=#565f89
palette = 9=#f7768e
palette = 10=#a6e3a1
palette = 11=#f9e2af
palette = 12=#7aa2f7
palette = 13=#cba6f7
palette = 14=#89dceb
palette = 15=#ffffff
